env:
  browser: true
  es2022: true
  node: true
extends:
  - plugin:prettier/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2022
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  '@typescript-eslint/no-explicit-any': off
